const state={categories:[],activeCategory:null,selected:null};const $=s=>document.querySelector(s);
function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2600)}
function cleanText(value){const holder=document.createElement('div');holder.innerHTML=String(value??'');return holder.textContent.replace(/\s+/g,' ').trim()}
function raisedPrice(value){const number=Number(value);return Number.isFinite(number)?Math.round(number*1.2*100)/100:0}
function formatAmount(value){const number=Number(value);if(!Number.isFinite(number))return'0';return Number.isInteger(number)?String(number):number.toFixed(2).replace(/0+$/,'').replace(/\.$/,'')}
function formatPrice(value){return formatAmount(raisedPrice(value))}
async function getJson(path){const data=window.CATALOG_DATA;if(data){if(path==='/api/categories')return data.categories||[];if(path.startsWith('/api/product/')){const id=path.split('/').pop();return{id:Number(id),description:(data.descriptions||{})[id]||''}}if(path.startsWith('/api/commodities')){const query=new URL(path,'http://static.local').searchParams;const categoryId=query.get('categoryId');const keywords=(query.get('keywords')||'').toLowerCase();return(data.items||[]).filter(item=>(!categoryId||String(item.category_id)===categoryId)&&(!keywords||cleanText(item.name).toLowerCase().includes(keywords)))}}const response=await fetch(path);if(!response.ok)throw new Error(`请求失败（${response.status}）`);const payload=await response.json();if(payload.code&&payload.code!==200)throw new Error(payload.msg||'接口返回错误');return payload.data||[]}
function renderCategories(){const list=$('#category-list');list.replaceChildren();for(const category of state.categories){const button=document.createElement('button');button.type='button';button.className=`chip${category.id===state.activeCategory?' active':''}`;const icon=document.createElement('span');icon.className='chip-icon';icon.textContent=cleanText(category.name).slice(0,1)||'◆';const name=document.createElement('span');name.textContent=cleanText(category.name);button.append(icon,name);button.addEventListener('click',()=>loadCategory(category.id));list.append(button)}}
function stockText(stock){const number=Number.parseInt(stock,10);if(Number.isNaN(number)||number<=0)return'较少';if(number>9999)return'非常多';return String(number)}
function renderProducts(items){const grid=$('#product-grid');grid.replaceChildren();if(!items.length){const empty=document.createElement('div');empty.className='loading';empty.textContent='该分类下没有商品，请点击其他分类';grid.append(empty);return}for(const item of items){const soldOut=Number.parseInt(item.stock,10)<=0;const card=document.createElement('article');card.className=`product-card${soldOut?' soldout':''}`;card.tabIndex=0;card.addEventListener('click',()=>openProduct(item));card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();openProduct(item)}});const cover=document.createElement('div');cover.className='product-cover';const info=document.createElement('div');info.className='product-info';const line=document.createElement('div');line.className='product-line';const name=document.createElement('div');name.className='product-name';name.textContent=cleanText(item.name);const price=document.createElement('div');price.className='product-price';price.textContent=`¥${formatPrice(item.price??item.user_price)}`;line.append(name,price);const stats=document.createElement('div');stats.className='product-stats';const stock=document.createElement('span');stock.textContent=`库存：${stockText(item.stock)}`;const sold=document.createElement('span');const soldValue=Number.parseInt(item.order_sold,10)||0;sold.textContent=`已售：${soldValue}`;if(soldValue>=100)sold.className='hot';stats.append(stock,sold);info.append(line,stats);card.append(cover,info);const badge=document.createElement('span');badge.className=`product-badge${soldOut?' sold':''}`;badge.textContent=soldOut?'售罄':soldValue>=100?'热卖':'';if(badge.textContent)card.append(badge);grid.append(card)}}
async function loadCategory(id){state.activeCategory=id;renderCategories();$('#product-grid').innerHTML='<div class="loading">努力加载中..</div>';try{renderProducts(await getJson(`/api/commodities?categoryId=${encodeURIComponent(id)}`))}catch(error){$('#product-grid').innerHTML=`<div class="loading">${error.message}，请重试</div>`}}
async function searchProducts(){const keywords=$('#search-input').value.trim();if(!keywords)return showToast('请输入要搜索的商品名称关键词');$('#product-grid').innerHTML='<div class="loading">努力加载中..</div>';try{renderProducts(await getJson(`/api/commodities?keywords=${encodeURIComponent(keywords)}`))}catch(error){$('#product-grid').innerHTML=`<div class="loading">${error.message}，请重试</div>`}}
function updateModalTotal(){const quantity=Math.max(1,Number.parseInt($('#quantity').value,10)||1);$('#quantity').value=quantity;$('#modal-total').textContent=`¥${formatAmount(raisedPrice(state.selected.price)*quantity)}`}
async function openProduct(item){state.selected=item;$('#modal-title').textContent=cleanText(item.name);$('#modal-price').textContent=`¥${formatPrice(item.price??item.user_price)}`;$('#modal-tags').innerHTML=`<span>库存：${stockText(item.stock)}</span><span>已售：${Number.parseInt(item.order_sold,10)||0}</span>`;$('#modal-description-content').textContent='详情加载中...';$('#modal-description-content').classList.remove('is-empty');$('#quantity').value='1';updateModalTotal();$('#product-modal').classList.add('open');$('#product-modal').setAttribute('aria-hidden','false');try{const payload=await getJson(`/api/product/${encodeURIComponent(item.id)}`);const description=String(payload.description||'').trim();if(state.selected!==item)return;$('#modal-description-content').textContent=description||'暂无商品介绍';if(!description)$('#modal-description-content').classList.add('is-empty')}catch(error){if(state.selected===item){$('#modal-description-content').textContent='商品介绍暂时无法加载';$('#modal-description-content').classList.add('is-empty')}}}
function closeModal(){$('#product-modal').classList.remove('open');$('#product-modal').setAttribute('aria-hidden','true');state.selected=null}
document.addEventListener('click',event=>{const action=event.target.closest('[data-action]')?.dataset.action;if(!action)return;if(action==='search')return searchProducts();if(action==='close-modal')closeModal();if(action==='minus'){$('#quantity').value=Math.max(1,Number.parseInt($('#quantity').value,10)-1);updateModalTotal()}if(action==='plus'){$('#quantity').value=Number.parseInt($('#quantity').value,10)+1;updateModalTotal()}if(action==='buy')showToast('目录展示模式暂不提交订单')});$('#quantity').addEventListener('input',updateModalTotal);$('#search-input').addEventListener('keydown',event=>{if(event.key==='Enter')searchProducts()});$('#product-modal').addEventListener('click',event=>{if(event.target.id==='product-modal')closeModal()});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeModal()});$('.menu-toggle').addEventListener('click',()=>{const nav=$('.nav-inner');const open=nav.classList.toggle('menu-open');$('.menu-toggle').setAttribute('aria-expanded',String(open))});
(async function init(){try{state.categories=await getJson('/api/categories');state.activeCategory=state.categories[0]?.id;renderCategories();if(state.activeCategory)await loadCategory(state.activeCategory)}catch(error){$('#category-list').innerHTML=`<div class="loading">${error.message}，请刷新重试</div>`;$('#product-grid').innerHTML=''}})();
